# Generated by Django 4.1.6 on 2023-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='client',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='update',
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.TextField(max_length=16, unique=True),
        ),
    ]
