# Generated by Django 4.1.6 on 2023-02-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_text_client_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='number',
            new_name='phone_number',
        ),
    ]
