# Generated by Django 4.1.6 on 2023-02-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_rename_number_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
