# Generated by Django 4.1.6 on 2023-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ManyToManyField(to='test_app.city'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.ManyToManyField(to='test_app.type'),
        ),
    ]
