# Generated by Django 4.1.6 on 2023-03-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
