# Generated by Django 4.1.6 on 2023-03-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_remove_client_city_remove_client_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_text',
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='video_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
