# Generated by Django 4.1.6 on 2023-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_remove_news_news_name_remove_news_news_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='news_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_5',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_6',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video_link',
        ),
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
