# Generated by Django 4.1.6 on 2023-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_rename_title_news_news_text_remove_news_paragraph_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_title',
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='video_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
