# Generated by Django 4.1.6 on 2023-03-29 13:44

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_rename_news_text_news_title_remove_news_news_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
