# Generated by Django 4.1.6 on 2023-03-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_alter_news_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
