# Generated by Django 4.1.6 on 2023-03-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_alter_news_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='paragraph_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_5',
        ),
        migrations.RemoveField(
            model_name='news',
            name='paragraph_6',
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
