# Generated by Django 4.1.6 on 2023-04-03 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_remove_news_paragraph_1_remove_news_paragraph_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
